spring:
  datasource:
    url: jdbc:postgresql://ec2-54-73-22-169.eu-west-1.compute.amazonaws.com:5432/d2g4mmslbrkc2v
    username: eficstkiiimibf
    password: 66d0917c6d1241e888861ecd653636e948e35f5aa0df744ff9ca54079c54b282

  #JPA Settings
  jpa:
    hibernate:
      ddl-auto: create