spring:
  datasource:
    url: jdbc:postgresql://cdgn4ufq38ipd0.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d4jggi2g7up3gr
    username: udbn3vic1dq2rf
    password: p3002d788ddee143f852b9d8ff2f8ae432281852cbb67b4079c1327fd70dd74d1



  #JPA Settings
  jpa:
    hibernate:
      ddl-auto: create


server:
  port: 8080